/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    Button: typeof import('./src/components/cs/button/index.vue')['default']
    CSButton: typeof import('./src/components/CSButton.vue')['default']
    Custom: typeof import('./src/components/cs/button/custom.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    ExpandablePanel: typeof import('./src/components/ExpandablePanel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageDisplay: typeof import('./src/components/ImageDisplay.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    MenuItems: typeof import('./src/components/menu-items.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavbarMenuItems: typeof import('./src/components/NavbarMenuItems.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./src/components/Services.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
